name: Build Docs

on:
  # 这将会在 `build/docs/` 目录中生成 `html5` 与 `pdf` 目录。
  push:
    branches: [ zh-Hans ]
  pull_request:
    branches: [ zh-Hans ]

  # 允许从“Actions”选项卡手动运行此工作流
  workflow_dispatch:

# 工作流运行由单个或多个工作组成，这些工作可以顺序运行或并行运行
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 在 $GITHUB_WORKSPACE 下签出仓库，以便工作可以访问它
      - uses: actions/checkout@v2

      - name: "构建文档"
        run: ./gradlew run

      - name: "部署到 GitHub Pages"
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          email: Yue_plus@foxmail.com
          build_dir: build/docs
